### ISSUE TITLE
Error lark.exceptions.UnexpectedToken: Unexpected token Token(COLON, ':')

### ISSUE THREAD

**Issue by schosterbarak** [amplify-education/python-hcl2#13]
Hello, I've encountered  `lark.exceptions.UnexpectedToken: Unexpected token Token(COLON, ':')`
error while parsing an output.tf that looks like:

```
output "ebs_sizes" {
  value = {
    "x" : 600,
    "y" : 350,
    "z" : 350,
    "xx" : 200
  }
}
```

did anyone encounter a similar issue?

**Comment by mikespub** [comment]
Probably because you should use = instead of : here?
As stated in https://www.terraform.io/docs/configuration/expressions.html

Maps/objects are represented by a pair of curly braces containing a series of <KEY> = <VALUE> pairs:

{
  name = "John"
  age  = 52
}

Key/value pairs can be separated by either a comma or a line break. Values can be arbitrary expressions. Keys are strings; they can be left unquoted if they are a valid identifier, but must be quoted otherwise. You can use a non-literal expression as a key by wrapping it in parentheses, like (var.business_unit_tag_name) = "SRE".

**Comment by schosterbarak** [comment]
thanks! it seems it is a change that was made between terraform 0.11 and 0.12. closing the issue
